// megafunction wizard: %PLL Intel FPGA IP v18.1%
// GENERATION: XML
// mf_audio_pll.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module mf_audio_pll (
    input  wire  refclk,
    input  wire  rst,
    output wire  outclk_0,
    output wire  outclk_1,
    output wire  locked
);

    mf_audio_pll_0002 mf_audio_pll_inst (
        .refclk   (refclk),
        .rst      (rst),
        .outclk_0 (outclk_0),
        .outclk_1 (outclk_1),
        .locked   (locked)
    );

endmodule
